// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: unittest.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace TridentUnitTest {
  public static partial class UnitTestService
  {
    static readonly string __ServiceName = "TridentUnitTest.UnitTestService";

    static readonly grpc::Marshaller<global::TridentUnitTest.TestRequest> __Marshaller_TridentUnitTest_TestRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TridentUnitTest.TestRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::TridentUnitTest.TestReply> __Marshaller_TridentUnitTest_TestReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::TridentUnitTest.TestReply.Parser.ParseFrom);

    static readonly grpc::Method<global::TridentUnitTest.TestRequest, global::TridentUnitTest.TestReply> __Method_UnitTest = new grpc::Method<global::TridentUnitTest.TestRequest, global::TridentUnitTest.TestReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UnitTest",
        __Marshaller_TridentUnitTest_TestRequest,
        __Marshaller_TridentUnitTest_TestReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::TridentUnitTest.UnittestReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of UnitTestService</summary>
    [grpc::BindServiceMethod(typeof(UnitTestService), "BindService")]
    public abstract partial class UnitTestServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::TridentUnitTest.TestReply> UnitTest(global::TridentUnitTest.TestRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for UnitTestService</summary>
    public partial class UnitTestServiceClient : grpc::ClientBase<UnitTestServiceClient>
    {
      /// <summary>Creates a new client for UnitTestService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public UnitTestServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for UnitTestService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public UnitTestServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected UnitTestServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected UnitTestServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::TridentUnitTest.TestReply UnitTest(global::TridentUnitTest.TestRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnitTest(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::TridentUnitTest.TestReply UnitTest(global::TridentUnitTest.TestRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UnitTest, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::TridentUnitTest.TestReply> UnitTestAsync(global::TridentUnitTest.TestRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UnitTestAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::TridentUnitTest.TestReply> UnitTestAsync(global::TridentUnitTest.TestRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UnitTest, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override UnitTestServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UnitTestServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(UnitTestServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_UnitTest, serviceImpl.UnitTest).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UnitTestServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_UnitTest, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::TridentUnitTest.TestRequest, global::TridentUnitTest.TestReply>(serviceImpl.UnitTest));
    }

  }
}
#endregion
